// site.mjs — assembles the static site (everything under site/) in memory.
//
// The design prototype ran React development builds and Babel in the browser from
// unpkg. Here, as in COMPOSE's build, esbuild transpiles each .jsx file to a
// classic script ahead of time and production React is served from site/assets.
// The files keep the prototype's structure: they still share one global scope
// (Object.assign(window, …) exports, top-level consts), exactly as when they were
// separate <script type="text/babel"> tags — so don't redeclare a top-level name
// in two files.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { transform } from 'esbuild';
import { buildData, renderDataJs } from './data.mjs';
import { buildDocs } from './docs.mjs';

// plain-JS modules shared by both apps, in load order
export const LEXICON = ['src/glossary.js', 'src/ahg.js', 'src/levin_classes.js', 'src/annotations.js',
  'src/nominals.js', 'src/frames.js', 'src/csv-export.js'];
export const EXPLORER = ['src/settings.jsx', 'src/engine.jsx', 'src/detail.jsx', 'src/views.jsx', 'src/app.jsx'];
export const JUDGE = ['src/judge-sync.js', 'src/judge-app.jsx'];

const read = (root, rel) => fs.readFileSync(path.join(root, rel), 'utf8').replace(/\r\n?/g, '\n');
const hash = (s) => crypto.createHash('sha256').update(s).digest('hex').slice(0, 10);
const banner = (what, from) => `// DACE ${what} — GENERATED by \`npm run build\` from ${from}. Do not edit by hand.\n`;

async function compileJsx(root, files) {
  const parts = [];
  for (const f of files) {
    const { code } = await transform(read(root, f), {
      loader: 'jsx', jsx: 'transform', jsxFactory: 'React.createElement', jsxFragment: 'React.Fragment',
      target: 'es2020', sourcefile: f,
    });
    parts.push(`// ---- ${f}\n${code}`);
  }
  return parts.join('\n');
}
const concat = (root, files) => files.map((f) => `// ---- ${f}\n${read(root, f).trimEnd()}\n`).join('\n');

function page(root, tpl, css, scripts) {
  const t = read(root, tpl);
  if (!t.includes('<!--DACE:CSS-->') || !t.includes('<!--DACE:SCRIPTS-->')) throw new Error(`${tpl}: missing <!--DACE:…--> placeholder`);
  return t.replace('<!--DACE:CSS-->', () => `<style>\n${read(root, css).trimEnd()}\n</style>`)
          .replace('<!--DACE:SCRIPTS-->', () => scripts);
}

/** Returns { files: { 'relative/path': string }, data } for everything in site/. */
export async function buildSite(root) {
  const files = {};
  const data = buildData(root);
  // React's package exports don't expose umd/, so read it from node_modules directly
  const umd = (m) => fs.readFileSync(path.join(root, 'node_modules', m), 'utf8').trimEnd() + '\n';

  files['assets/react.js'] = umd('react/umd/react.production.min.js') + umd('react-dom/umd/react-dom.production.min.js');
  // Judge only: sign-in + judgement sync (the .map isn't shipped, so drop the pointer to it)
  files['assets/pocketbase.js'] = umd('pocketbase/dist/pocketbase.umd.js').replace(/\n\/\/# sourceMappingURL=\S*\n?$/, '\n');
  files['assets/data.js'] = renderDataJs(data);
  files['assets/lexicon.js'] = banner('lexicon modules', 'src/*.js') + concat(root, LEXICON);
  files['assets/explorer.js'] = banner('Explorer', 'src/*.jsx') + await compileJsx(root, EXPLORER);
  files['assets/judge.js'] = banner('Judge', 'src/judge-sync.js + src/judge-app.jsx') + await compileJsx(root, JUDGE);
  Object.assign(files, buildDocs(root, data.stats));
  files['data/predicates.csv'] = read(root, 'data/predicates.csv');
  if (fs.existsSync(path.join(root, 'data/cells.csv'))) files['data/cells.csv'] = read(root, 'data/cells.csv');
  files['favicon.svg'] = read(root, 'src/favicon.svg');
  files['robots.txt'] = 'User-agent: *\nDisallow: /judge/\n';

  // ?v=<content hash> so browsers pick up new assets as soon as the page changes
  const tags = (prefix, names) => names.map((n) => `<script src="${prefix}assets/${n}?v=${hash(files['assets/' + n])}"></script>`).join('\n');
  files['index.html'] = page(root, 'src/explorer.html', 'src/explorer.css', tags('', ['react.js', 'data.js', 'lexicon.js', 'explorer.js']));
  files['judge/index.html'] = page(root, 'src/judge.html', 'src/judge.css', tags('../', ['react.js', 'pocketbase.js', 'data.js', 'lexicon.js', 'judge.js']));
  return { files, data };
}

export function writeSite(outDir, files) {
  fs.rmSync(outDir, { recursive: true, force: true });
  for (const [rel, content] of Object.entries(files)) {
    const p = path.join(outDir, rel);
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
  }
}

export function listFiles(dir) {
  const out = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...listFiles(p)); else out.push(p);
  }
  return out;
}
